os: linux
dist: trusty
sudo: true

arch:
  - AMD64
  - ppc64le 

compiler:
  - gcc

addons:
  apt:
    packages:
    - libexiv2-dev

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -q
    - sudo apt-get install -y qt58-meta-minimal
script:
    - source /opt/qt58/bin/qt58-env.sh
    - qmake
    - make -j2
